[alembic]
# Tell Alembic where the migration environment files live
script_location = alembic

# Template used to name migration files (e.g. 1a2b3c4d_add_created_by.py)
file_template = %%(rev)s_%%(slug)s

prepend_sys_path = .
version_path_separator = os

[logging]
default_handler = console

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(name)s] %(levelname)-5s: %(message)s
datefmt = %H:%M:%S