services:

  # postgres
  db:
    image: pgvector/pgvector:pg14
    container_name: npi_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: npi_user
      POSTGRES_PASSWORD: npi_password
      POSTGRES_DB: npi_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  # minio
  minio:
    image: minio/minio
    container_name: npi_minio_container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER : minioadmin
      MINIO_ROOT_PASSWORD : minioadmin
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    restart: always


volumes:
  pgdata:
  miniodata: